import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { NextAuthProvider, ThemeProvider } from "@/components/provider";
import NavHeader from "@/components/navigation/nav-header";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <NextAuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="relative flex min-h-screen flex-col bg-background">
              <NavHeader />
              <main className="flex-1">
                <div className="container mx-auto px-8 py-12">{children}</div>
              </main>
            </div>
            <Toaster richColors />
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
